# Generated by Django 3.2.8 on 2021-10-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profiles_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_email',
        ),
    ]
