# Generated by Django 4.1.1 on 2022-10-21 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_post_no_of_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=5000)),
                ('requirements', models.CharField(max_length=5000)),
                ('job_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('is_remote', models.BooleanField()),
                ('is_featured', models.BooleanField()),
                ('apply_link', models.URLField(max_length=20000)),
            ],
        ),
    ]
