# Generated by Django 4.1.1 on 2022-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_jobs_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='tags',
            field=models.ManyToManyField(blank=True, to='projects.tag'),
        ),
    ]
