# Generated by Django 4.1.1 on 2022-10-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_jobs_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='demo_video',
            field=models.URLField(default='https://www.youtube.com/watch?v=hugKn8A7h3U', max_length=20000),
            preserve_default=False,
        ),
    ]
