# Generated by Django 4.1.1 on 2022-11-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20221106_0946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
